const assert = require('assert')

const importer = require('./add-2012-immaculate-numbers-patch')

const subsetDocs = importer.buildSubsetDocs()
const items = subsetDocs.flatMap(doc => doc.items || [])
const seriesDoc = importer.buildSeriesDoc(subsetDocs)
const summary = importer.summarize(subsetDocs)

assert.strictEqual(subsetDocs.length, 1)
assert.strictEqual(subsetDocs[0].subset, 'Numbers Patch')
assert.strictEqual(items.length, 100)
assert.strictEqual(items[0].text, '1 Al Horford')
assert.strictEqual(items[0].printRun, 15)
assert.strictEqual(items[13].text, '14 Derrick Rose')
assert.strictEqual(items[13].printRun, 1)
assert.strictEqual(items[43].text, '44 Kobe Bryant')
assert.strictEqual(items[43].printRun, 24)
assert.strictEqual(items[52].text, '53 LeBron James')
assert.strictEqual(items[52].printRun, 6)
assert.strictEqual(items[70].text, '71 Russell Westbrook')
assert.strictEqual(items[70].printRun, 100)
assert.strictEqual(items[99].text, '100 Nene')
assert.strictEqual(items[99].printRun, 42)
assert.strictEqual(items.every(item => item.cardKind === 'Numbers Patch'), true)
assert.strictEqual(items.every(item => item.completionTarget === item.printRun), true)
assert.strictEqual(items.every(item => item.player), true)
assert.strictEqual(items.find(item => item.player === 'LeBron James').playerCN, '勒布朗·詹姆斯')

assert.strictEqual(seriesDoc.name, '2012-13 Panini Immaculate Numbers Patch')
assert.strictEqual(seriesDoc.defaultYear, '2012-13')
assert.strictEqual(seriesDoc.defaultBrand, 'Panini')
assert.strictEqual(seriesDoc.defaultCardSeries, 'Immaculate')
assert.strictEqual(seriesDoc.defaultCardKind, 'Numbers Patch')
assert.strictEqual(seriesDoc.checklistComplete, true)
assert.strictEqual(seriesDoc.totalCards, 1840)
assert.strictEqual(seriesDoc.listTotalCount, 1840)
assert.deepStrictEqual(seriesDoc.presetCardKinds.map(item => item.value), ['Numbers Patch'])
assert(seriesDoc.presetNumbers.some(item => item.value === '/1'))
assert(seriesDoc.presetNumbers.some(item => item.value === '/100'))
assert(seriesDoc.description.includes('球衣号码 Patch'))

assert.strictEqual(summary.itemCount, 100)
assert.strictEqual(summary.totalCards, 1840)
assert.strictEqual(summary.first, '1 Al Horford #/15')
assert.strictEqual(summary.last, '100 Nene #/42')

console.log('2012 Immaculate Numbers Patch importer tests passed')
