const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const importer = require('./add-1998-carddass-slam-dunk')
const pageJs = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.js'), 'utf8')
const pageWxml = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.wxml'), 'utf8')
const pageWxss = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.wxss'), 'utf8')
const appWxss = fs.readFileSync(path.join(root, 'miniprogram-card/app.wxss'), 'utf8')

const seriesDoc = importer.buildSeriesDoc(importer.buildSubsetDocs())

assert.strictEqual(seriesDoc.displayMode, 'fixedImageGrid')

assert(pageJs.includes("displayMode === 'fixedImageGrid'"), 'collection-series.js should detect fixed image grid series')
assert(pageJs.includes('_parseFixedGridCardText'), 'collection-series.js should parse fixed grid card text')
assert(pageJs.includes('_buildFixedGridCardMeta'), 'collection-series.js should build fixed grid card metadata')
assert(pageJs.includes('_buildFixedImageGridGroup'), 'collection-series.js should flatten fixed grid cards into one group')
assert(pageJs.includes('_getFixedGridSortRank'), 'collection-series.js should sort fixed grid cards by fixed slot number')
assert(pageJs.includes('_getChecklistUploadDefaults'), 'collection-series.js should prefill fixed slot upload metadata')
assert(pageJs.includes('uploadFixedSlot'), 'collection-series.js should mark fixed slot uploads')
assert(pageJs.includes('fixedGridPureMode'), 'collection-series.js should track fixed grid pure image mode')
assert(pageJs.includes('toggleFixedGridPureMode'), 'collection-series.js should toggle fixed grid pure image mode')
assert(pageJs.includes('imageGridColumns'), 'collection-series.js should track shared grid columns')
assert(pageJs.includes('cycleImageGridViewMode'), 'collection-series.js should cycle shared grid columns')
assert(pageJs.includes('_getFixedGridPreviewUrls'), 'collection-series.js should build a full fixed grid preview group')
assert(pageJs.includes('if (this._isFixedImageGridMode() || this._isFixedCardSlotMode())'), 'fixed grid preview should use fixed-grid context')
assert(pageJs.includes('urls.push(...images.map(img => img && img.url).filter(Boolean))'), 'fixed grid preview should include every uploaded image, not only representative grid images')
assert(pageJs.includes('_uniquePreviewUrls'), 'preview groups should de-duplicate image URLs')

assert(pageWxml.includes('fixed-grid-section'), 'collection-series.wxml should render a fixed grid section')
assert(pageWxml.includes('fixedGridPureMode ?'), 'collection-series.wxml should react to fixed grid pure image mode')
assert(pageWxml.includes('toggleFixedGridPureMode'), 'collection-series.wxml should render a fixed grid pure image toggle')
assert(pageWxml.includes('bindtap="cycleImageGridViewMode">布局·{{imageGridViewLabel}}</view>'), 'collection-series.wxml should render a shared grid column layout toggle')
assert(pageWxml.includes("{{fixedGridPureMode ? '纯图模式' : '上传模式'}}"), 'fixed grid view toggle should show the current pure/upload mode')
assert(!pageWxml.includes("{{fixedGridPureMode ? '卡种' : '纯图'}}"), 'fixed grid view toggle should not use pure/card wording')
assert(pageWxml.includes('mode="aspectFit"'), 'fixed grid thumbnails should use the previous checklist aspectFit style')
assert(pageWxml.includes('class="fixed-grid-top-labels"'), 'fixed grid should group top labels in one row to avoid overlap')
assert(pageWxml.includes('class="fixed-grid-label fixed-grid-number-label"'), 'fixed grid should show uploaded numbers in the top label row')
assert(pageWxml.includes('class="fixed-grid-label fixed-grid-card-kind-label"'), 'fixed grid should show uploaded card kinds in the top label row')
assert(pageWxml.includes('wx:if="{{!(isFixedImageGrid && fixedGridPureMode) && !card._gridImage}}" class="fixed-grid-meta"'), 'fixed grid should only show bottom metadata for empty slots')
assert(pageWxml.includes('wx:if="{{((!fixedGridPureMode && !isDerivedThemeSeries) || card._gridImage) && !card._filterHidden}}"'), 'fixed grid should hide empty upload placeholders and filtered cards in pure/search modes')
assert(!pageWxml.includes('fixed-grid-target-btn'), 'fixed grid images should not show a separate card-kind edit button')
assert(!pageWxml.includes('fixed-grid-complete-label'), 'fixed grid images should not show completion checkmarks on thumbnails')
assert(pageWxml.includes('wx:if="{{item.subset && !isFixedImageGrid && !item._hideTitle}}"'), 'collection-series.wxml should hide subset titles in fixed grid mode')
assert(pageWxml.includes('wx:if="{{!isFreeMode && !isFixedImageGrid && checklistGroups.length > 0}}"'), 'collection-series.wxml should hide collapse controls in fixed grid mode')
assert(!pageWxml.includes('wx:if="{{(isFixedImageGrid || isFixedCardSlots) && (canContribute || canManageSeries)}}" class="action-btn action-btn-upload"'), 'fixed image-grid collections should not show a global top upload action')
assert(pageWxml.includes('wx:if="{{isFreeMode || !isFixedImageGrid}}" class="modal-section"'), 'collection-series.wxml should hide legacy structure settings in fixed grid mode')
assert(pageWxml.includes('wx:if="{{!isFreeMode && !isFixedImageGrid}}" class="modal-section manage-subset-list"'), 'collection-series.wxml should hide legacy subset management in fixed grid mode')
assert(pageWxml.includes('fixed-grid-card'), 'collection-series.wxml should render fixed grid cards')
assert(!pageWxml.includes('fixed-grid-card-has-image'), 'fixed grid should use the same neutral card shell for uploaded and empty slots')
assert(pageWxml.includes('fixed-grid-placeholder'), 'collection-series.wxml should render fixed grid upload placeholders')
assert(pageWxml.includes('fixed-grid-card-name'), 'collection-series.wxml should render fixed grid card names')

assert(pageWxss.includes('.fixed-grid-card'), 'collection-series.wxss should style fixed grid cards')
assert(!pageWxss.includes('.fixed-grid-card-has-image'), 'fixed grid should not use a special dark uploaded card shell')
assert(pageWxss.includes('.fixed-grid-placeholder'), 'collection-series.wxss should style fixed grid placeholders')
assert(pageWxss.includes('.fixed-grid-image'), 'collection-series.wxss should style fixed grid images')
assert(!pageWxss.includes('transform: scale(1.025)'), 'fixed grid should not overscan/crop images')
assert(!pageWxss.includes('fixed-grid-image-number-label'), 'fixed grid should not style overlaid number labels')
assert(!pageWxss.includes('fixed-grid-image-name-label'), 'fixed grid should not style overlaid card kind labels')
assert(appWxss.includes('.fixed-grid-top-labels'), 'fixed grid should style a shared top label row')
assert(appWxss.includes('.fixed-grid-label'), 'fixed grid should style shared top label chips')
assert(appWxss.includes('.fixed-grid-number-label + .fixed-grid-card-kind-label'), 'fixed grid label widths should prevent number/card kind overlap')
assert(appWxss.includes('background: rgba(0, 0, 0, 0.55)'), 'fixed grid card kind labels should use the previous badge background')
assert(appWxss.includes('top: 6rpx'), 'fixed grid top label row should pin to the image top edge')
assert(pageWxss.includes('grid-template-columns: repeat(3, minmax(0, 1fr))'), 'fixed grid should spread three columns across the available width')
assert(!pageWxss.includes('.fixed-grid-section-pure { grid-template-columns'), 'pure image mode should not override the shared 3/2/1 column layout')
assert(pageWxss.includes('.fixed-grid-section.image-grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr))'), 'fixed grid should provide an explicit two-column layout option')
assert(pageWxss.includes('aspect-ratio: 109 / 142'), 'fixed grid image boxes should keep the previous card slot ratio')
assert(!pageWxss.includes('.fixed-grid-card { width: 218rpx;'), 'fixed grid cards should not use a hard-coded width')
assert(!pageWxss.includes('width: 218rpx; height: 284rpx'), 'fixed grid image boxes should not use hard-coded width and height')
assert(pageWxss.includes('.fixed-grid-image-wrap .image-remove-btn'), 'fixed grid should override delete button placement')
assert(pageWxss.includes('top: 8rpx; right: 8rpx'), 'fixed grid delete button should sit inside the image corner')

console.log('fixed image grid mode tests passed')
