const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const indexJs = fs.readFileSync(path.join(root, 'miniprogram-card/pages/index/index.js'), 'utf8')
const indexWxml = fs.readFileSync(path.join(root, 'miniprogram-card/pages/index/index.wxml'), 'utf8')
const collectionJs = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.js'), 'utf8')
const seriesOps = fs.readFileSync(path.join(root, 'miniprogram-card/cloudfunctions/seriesOps/index.js'), 'utf8')
const querySeries = fs.readFileSync(path.join(root, 'card/query-series.js'), 'utf8')

assert(indexJs.includes("structureType: 'freeImage'"), 'create form should store a structureType')
assert(indexJs.includes("value: 'fixedChecklist'"), 'create form should expose fixed checklist structure')
assert(indexJs.includes('fixedChecklistText'), 'create form should collect fixed checklist card slots')
assert(indexJs.includes('fixedChecklistPlaceholder'), 'fixed checklist textarea should bind multiline placeholder from js data')
assert(indexJs.includes('parseFixedChecklistLines'), 'index.js should parse fixed checklist lines')
assert(indexJs.includes("replace(/^#/, '')"), 'fixed checklist parser should accept # prefixed numbers')
assert(indexJs.includes('structureType,'), 'fixed checklist series should persist structureType')
assert(indexJs.includes("displayMode = 'fixedImageGrid'"), 'fixed checklist series should persist fixed image grid display mode')

assert(indexWxml.includes('structureTypeOptions'), 'create modal should render structure type options')
assert(indexWxml.includes('固定卡位'), 'create modal should show fixed checklist label')
assert(indexWxml.includes('fixedChecklistText'), 'create modal should include fixed checklist textarea')
assert(indexWxml.includes('placeholder="{{fixedChecklistPlaceholder}}"'), 'fixed checklist placeholder should use js-bound multiline text')
assert(!indexWxml.includes('&#10;'), 'fixed checklist placeholder should not render literal newline entities')

assert(collectionJs.includes("structureType === 'fixedChecklist'"), 'collection series should detect fixed checklist structure')
assert(collectionJs.includes("replace(/^#/, '')"), 'fixed grid display parser should accept # prefixed numbers')
assert(seriesOps.includes("'structureType'"), 'seriesOps should allow structureType updates')
assert(seriesOps.includes("'displayMode'"), 'seriesOps should allow displayMode updates')
assert(querySeries.includes('structureType'), 'query-series should expose structureType for verification')
assert(querySeries.includes('displayMode'), 'query-series should expose displayMode for verification')

console.log('fixed checklist structure tests passed')
