const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const pageJs = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.js'), 'utf8')
const pageWxml = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.wxml'), 'utf8')
const pageWxss = fs.readFileSync(path.join(root, 'miniprogram-card/pages/collection-series/collection-series.wxss'), 'utf8')
const importer = require('./add-2016-hoops-rttf-cavs')

const subsetDocs = importer.buildSubsetDocs()
const seriesDoc = importer.buildSeriesDoc(subsetDocs)

assert.strictEqual(seriesDoc.displayMode, 'fixedCardSlots')
assert(pageJs.includes('_isFixedCardSlotSeries'), 'collection-series.js should detect fixed card slot series')
assert(pageJs.includes("series.displayMode === 'fixedCardSlots'"), 'fixed card slot display should be driven by displayMode')
assert(subsetDocs.every(doc => doc.items.every(item => item.completionTarget === 1)), 'single-card fixed slots should use completionTarget 1')
assert(pageJs.includes('if (isFixedImageGrid || isFixedCardSlots)'), 'fixed slots should reuse fixed-card grid metadata')
assert(pageJs.includes('if (isFixedImageGrid) return [this._buildFixedImageGridGroup(groupOrder)]'), 'only flat fixed-image grids should collapse groups')
assert(pageJs.includes('!this._isFixedImageGridMode() && !this._isFixedCardSlotMode()'), 'fixed slots should carry number/card kind defaults on upload')
assert(!pageJs.includes('|| normalizedItem._fixedCardSlot'), 'fixed slots should not force regular progress slot rendering')
assert(pageWxml.includes('(isFixedImageGrid || isFixedCardSlots) && !collapsedSubsets[item.subset]'), 'fixed slots should render as fixed-card grid under each subset')
assert(!pageWxml.includes('(isFixedImageGrid || isFixedCardSlots) && (canContribute || canManageImages)}}" class="action-btn action-btn-upload"'), 'fixed card/slot collections should not expose a global top upload action')
assert(pageWxml.includes('bindtap="cycleImageGridViewMode">布局·{{imageGridViewLabel}}</view>'), 'all collection details should expose the shared layout switch')
assert(pageJs.includes('imageGridColumns'), 'collection detail should track a shared column view mode')
assert(pageJs.includes('cycleImageGridViewMode'), 'collection detail should cycle 3/2/1 column layouts')
assert(pageWxml.includes('bindtap="cycleImageGridViewMode">布局·{{imageGridViewLabel}}</view>'), 'collection detail should expose a shared column layout switch')
assert(!pageWxml.includes('toggleImageViewMode'), 'collection detail should not expose a separate large/small image mode switch')
assert(!pageJs.includes('imageViewMode'), 'collection detail should only use 3/2/1 column layout state')
assert(!pageJs.includes('previewFixedCardSlotImages'), 'fixed slots top view action should not directly preview images')
assert(pageJs.includes('this._isFixedImageGridMode() || this._isFixedCardSlotMode()'), 'fixed slot image previews should still scroll uploaded fixed-slot images')
assert(pageWxml.includes("isFixedImageGrid && fixedGridPureMode ? 'fixed-grid-section-pure' : ''"), 'fixed image grid pure mode should stay scoped to fixed image grids')
assert(pageWxml.includes('image-grid-cols-{{imageGridColumns}}'), 'collection image grids should support dynamic 3/2/1 column view')
assert(pageWxml.includes('class="image-preview-icon"'), 'collection images should expose a lower-right preview icon')
assert(pageWxml.includes('catchtap="previewSingleImage"'), 'preview icons should open the image preview without entering card detail')
assert(pageWxml.includes('card._gridImage._showOwned'), 'fixed grid thumbnails should preserve the owned banner')
assert(pageWxml.includes('slot.image._showOwned'), 'print-run slot thumbnails should preserve the owned banner')
assert(pageJs.includes('_getChecklistItemPreviewUrls'), 'regular card-kind previews should swipe through images under the same checklist item')
assert(pageJs.includes('urls.push(...images.map(img => img && img.url).filter(Boolean))'), 'fixed-grid previews should include every image in fixed slots, not only visible primary tiles')
assert(pageWxml.includes('class="fixed-grid-top-labels"'), 'fixed slots should render number and card kind in one top label row')
assert(pageWxml.includes('!(isFixedImageGrid && fixedGridPureMode) && !card._gridImage'), 'fixed slot placeholders should keep bottom metadata outside fixed image pure mode')
assert(pageWxss.includes('.fixed-grid-section.image-grid-cols-3'), 'fixed slots should style three-column view')
assert(pageWxss.includes('.fixed-grid-section.image-grid-cols-2'), 'fixed slots should style two-column view')
assert(pageWxss.includes('.fixed-grid-section.image-grid-cols-1'), 'fixed slots should style one-column view')
assert(pageWxss.includes('.fixed-grid-number-label + .fixed-grid-card-kind-label'), 'fixed slots should constrain top labels so they do not overlap in three columns')
assert(pageWxss.includes('.view-small.image-grid-cols-3'), 'regular checklist image grids should share three-column styling')
assert(pageWxss.includes('.free-images.view-small.image-grid-cols-3'), 'free image grids should share three-column styling')
assert(!pageWxml.includes("imageViewMode === 'small' || card._fixedCardSlot"), 'fixed slots should not use regular small progress slots')

console.log('fixed card slots display tests passed')
