const assert = require('assert')
const fs = require('fs')
const path = require('path')
const vm = require('vm')

const root = path.resolve(__dirname, '..')

function read(file) {
  return fs.readFileSync(path.join(root, file), 'utf8')
}

function test(name, fn) {
  try {
    fn()
    console.log(`ok - ${name}`)
  } catch (err) {
    console.error(`not ok - ${name}`)
    throw err
  }
}

test('1986 Fleer checklist players are covered by roster data', () => {
  const collectionSource = read('card/js/collection-data.js')
  const ctx = {}
  vm.runInNewContext(`${collectionSource}\nthis.collectionData = collectionData;`, ctx)
  const series = (ctx.collectionData || []).find((item) => item.name === '1986 Fleer')
  assert(series, 'missing 1986 Fleer collection')

  const roster = JSON.parse(read('scripts/data/nba-players-roster.json'))
  const extra = JSON.parse(read('scripts/data/nba-players-extra.json'))
  const bundledRoster = require(path.join(root, 'miniprogram-card/utils/nbaPlayersRoster.js'))
  const rosterNames = new Set([...roster, ...extra, ...bundledRoster].map((player) => player.enName))
  const missing = [...new Set((series.checklist || []).map((item) => String(item.text || '')
    .replace(/^\d+\s+/, '')
    .replace(/\s+-\s+.*$/, '')
    .replace(/\s+RC$/, '')
    .trim()))]
    .filter((name) => name && name !== 'Checklist' && !rosterNames.has(name))

  assert.deepStrictEqual(missing, [])
  assert(rosterNames.has('Jeff Malone'), 'Jeff Malone should be available in the bundled roster fallback')
})

test('Slam Dunk card subjects are covered by roster data', () => {
  const roster = JSON.parse(read('scripts/data/nba-players-roster.json'))
  const extra = JSON.parse(read('scripts/data/nba-players-extra.json'))
  const bundledRoster = require(path.join(root, 'miniprogram-card/utils/nbaPlayersRoster.js'))
  const playerRoster = require(path.join(root, 'miniprogram-card/utils/playerRoster.js'))
  const allRoster = [...roster, ...extra, ...bundledRoster]
  const rosterNames = new Set(allRoster.map((player) => player.enName))
  ;[
    'Hanamichi Sakuragi',
    'Kaede Rukawa',
    'Takenori Akagi',
    'Hisashi Mitsui',
    'Ryota Miyagi',
    'Akira Sendoh',
    'Shinichi Maki',
    'Eiji Sawakita'
  ].forEach((name) => {
    assert(rosterNames.has(name), `${name} should be available for Slam Dunk card entry`)
  })
  assert.strictEqual(playerRoster.findPlayerMeta(allRoster, '樱木花道').enName, 'Hanamichi Sakuragi')
  assert.strictEqual(playerRoster.findPlayerMeta(allRoster, '流川').enName, 'Kaede Rukawa')
  assert.strictEqual(playerRoster.findPlayerMeta(allRoster, '三井').enName, 'Hisashi Mitsui')
})

test('catalog enum caches are invalidated by remote manifest versions', () => {
  const collectionDataJs = read('miniprogram-card/utils/collectionData.js')
  const appJs = read('miniprogram-card/app.js')
  const taxonomyJs = read('miniprogram-card/utils/cardTaxonomy.js')
  const manifest = JSON.parse(read('scripts/data/card-catalog-manifest.json'))
  const catalogOptions = JSON.parse(read('scripts/data/card-catalog-options.json'))
  const bundledTeams = require(path.join(root, 'miniprogram-card/utils/nbaTeamsRoster.js'))

  assert(collectionDataJs.includes('CATALOG_MANIFEST_PATH = \'static/card-catalog-manifest.json\''), 'collection data should load a remote catalog manifest')
  assert(collectionDataJs.includes('CATALOG_MANIFEST_MAX_AGE = 5 * 60 * 1000'), 'manifest should be refreshed during long-running app sessions')
  assert(collectionDataJs.includes('catalogUrl(CATALOG_MANIFEST_PATH)'), 'manifest requests should bypass stale data with a timestamp URL')
  assert(collectionDataJs.includes('readVersionedCache(PLAYERS_CACHE_KEY, version, validator)'), 'players cache should be keyed by manifest version')
  assert(collectionDataJs.includes('readVersionedCache(TEAMS_CACHE_KEY, version, validator)'), 'teams cache should be keyed by manifest version')
  assert(collectionDataJs.includes('readVersionedCache(CARD_CATALOG_OPTIONS_CACHE_KEY, version, validator)'), 'card catalog options cache should be keyed by manifest version')
  assert(collectionDataJs.includes('loadCatalogVersionToken'), 'collection data should expose a version token for dependent caches')
  assert(appJs.includes('loadCatalogVersionToken'), 'suggestion cache should compare against the current catalog version')
  assert(appJs.includes('data.catalogVersion === catalogVersion'), 'suggestion cache should be invalidated when catalog versions change')
  assert(taxonomyJs.includes('function buildBrandOptions(cards = [], options = {})'), 'brand options should accept remote taxonomy options')
  assert(taxonomyJs.includes('function buildSeriesOptions(cards = [], options = {})'), 'series options should accept remote taxonomy options')
  assert.strictEqual(manifest.players.version, '2026-05-13-2003-slam-dunk-v1')
  assert.strictEqual(manifest.players.path, 'static/nba-players-roster-2003-slam-dunk-v1.json')
  assert.strictEqual(manifest.players.minCount, 2003)
  assert.strictEqual(manifest.teams.minCount, bundledTeams.length)
  assert.strictEqual(manifest.cardCatalogOptions.version, '2026-05-12-card-taxonomy-v2')
  assert.strictEqual(manifest.cardCatalogOptions.minBrands, 41)
  assert.strictEqual(manifest.cardCatalogOptions.minSeries, 229)
  assert(Array.isArray(catalogOptions.brands) && catalogOptions.brands.includes('Panini'))
  assert(Array.isArray(catalogOptions.series) && catalogOptions.series.includes('Prizm'))
  assert(catalogOptions.brands.includes('Bandai'), 'manufacturer suggestions should include common Japanese card makers')
  assert(catalogOptions.series.includes('PhotoGenic'), 'post-2012 Panini suggestions should include newer standalone lines')
  assert(catalogOptions.series.includes('Brilliance'), 'post-2012 Panini suggestions should include early Panini lines')
  assert(catalogOptions.series.includes('Topps Pristine'), 'pre-2012 suggestions should include popular Topps lines')
  assert(catalogOptions.series.includes('SkyBox Premium'), 'pre-2012 suggestions should include popular Fleer/SkyBox lines')
  assert(catalogOptions.seriesAliases.Prizm.includes('金折'), 'existing aliases should remain intact')
})

test('collection card detail handles standalone user cards without a series', () => {
  const js = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  assert(js.includes('function normalizeSeriesCardFeatures(series = {})'))
  assert(js.includes('series = series || {}'))
})

test('upload modal is cleared only after a successful upload', () => {
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const start = js.indexOf('async confirmUpload()')
  const body = js.slice(start, js.indexOf('\n  removeCardImage', start))
  assert(start >= 0, 'missing confirmUpload')
  assert(!body.includes('this.setData({ showUploadModal: false })'), 'upload modal should not close before async work finishes')
  assert(body.includes('this.closeUploadModal()'), 'successful upload should close and clear modal state')
})

test('collection series upload modal uses full-width image pickers', () => {
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const wxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  assert(wxml.includes('upload-scroll upload-form-scroll series-upload-scroll'))
  assert(wxml.includes('upload-scroll upload-form-scroll series-upload-scroll edit-image-scroll'), 'edit image modal should reuse the same full-width image upload layout')
  assert(wxml.includes('class="upload-thumb" src="{{item.tempFilePath}}" mode="aspectFit"'))
  assert(wxml.includes('class="upload-thumb" src="{{editImageUrl}}" mode="aspectFit"'), 'edit image front preview should match upload modal aspect-fit behavior')
  assert(wxss.includes('.series-upload-scroll .upload-face-block'))
  assert(wxss.includes('flex: 1; width: auto; height: 300rpx'))
  assert(wxss.includes('.series-upload-scroll .upload-image-btn'))
})

test('collection series manage modal supports default meta suggestions', () => {
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const rules = read('miniprogram-card/PRODUCT_RULES.md')
  assert(wxml.includes('value="{{item.year}}" data-i="{{index}}" data-field="year" bindfocus="onUploadMetaSuggestFocus" bindinput="onUploadItemYear"'), 'upload image year should use the shared suggestion input')
  assert(wxml.includes("activeUploadSuggest === 'year' && uploadSuggestIdx === index && uploadSuggestFiltered.length > 0"), 'upload image year should render a dropdown suggestion list')
  assert(wxml.includes('value="{{editImageYear}}" data-field="year" bindfocus="onEditMetaSuggestFocus" bindinput="onEditImageYear"'), 'edit image year should use the shared suggestion input')
  assert(wxml.includes("activeEditSuggest === 'year' && editSuggestFiltered.length > 0"), 'edit image year should render a dropdown suggestion list')
  assert(wxml.includes('value="{{editSeriesDefaultYear}}" data-field="year" bindfocus="onManageMetaSuggestFocus" bindinput="onEditSeriesDefaultYear"'), 'default year should use the manage suggestion input')
  assert(wxml.includes("activeManageSuggest === 'year' && manageSuggestFiltered.length > 0"), 'default year should render a dropdown suggestion list')
  assert(wxml.includes('value="{{editSeriesDefaultBrand}}" data-field="brand" bindfocus="onManageMetaSuggestFocus" bindinput="onEditSeriesDefaultBrand"'), 'default brand should use the manage suggestion input')
  assert(wxml.includes("activeManageSuggest === 'brand' && manageSuggestFiltered.length > 0"), 'default brand should render a dropdown suggestion list')
  assert(wxml.includes('value="{{editSeriesDefaultCardSeries}}" data-field="cardSeries" bindfocus="onManageMetaSuggestFocus" bindinput="onEditSeriesDefaultCardSeries"'), 'default series should use the manage suggestion input')
  assert(wxml.includes("activeManageSuggest === 'cardSeries' && manageSuggestFiltered.length > 0"), 'default series should render a dropdown suggestion list')
  assert(js.includes("const META_SUGGEST_FIELDS = ['player', 'year', 'brand', 'cardSeries']"), 'all card metadata suggestions should allow player, year, brand and series')
  assert(js.includes('_getManageSuggestValue(field)'), 'manage meta suggestions should read the active default field value')
  assert(js.includes("this.filterUploadSuggestions('year', i, value)"), 'upload year input should filter year suggestions')
  assert(js.includes("this.filterEditSuggestions('year', value)"), 'edit year input should filter year suggestions')
  assert(js.includes('update.editSeriesDefaultYear = value'), 'manage suggestion selection should fill the default year')
  assert(js.includes('update.editSeriesDefaultBrand = value'), 'manage suggestion selection should fill the default brand')
  assert(js.includes('update.editSeriesDefaultCardSeries = value'), 'manage suggestion selection should fill the default series')
  assert(rules.includes('图鉴默认信息、上传图片、编辑图片里的年份、球员、厂商、系列等有建议数据的字段，都需要复用建议数据并支持搜索和下拉选择'), 'product rules should document searchable metadata fields across collection forms')
})

test('fixed card slots keep an upload entrance after one image exists', () => {
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const wxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  const start = wxml.indexOf('<view wx:if="{{card._gridImage}}" class="fixed-grid-image-wrap')
  const end = wxml.indexOf('<view wx:else class="fixed-grid-placeholder"', start)
  const imageBlock = wxml.slice(start, end)
  assert(start >= 0 && end > start, 'missing fixed grid image block')
  assert(imageBlock.includes('class="fixed-grid-add-btn"'), 'existing fixed slot images need a visible upload entrance')
  assert(imageBlock.includes('data-idx="{{card._idx}}"'), 'upload entrance should target the same fixed slot')
  assert(imageBlock.includes('catchtap="addCardImage"'), 'upload entrance should append through the existing upload flow')
  assert(wxss.includes('.fixed-grid-add-btn'), 'upload entrance needs explicit overlay styling')
  assert(wxss.includes('.fixed-grid-add-btn { position: absolute; left: 8rpx; bottom: 8rpx;'), 'upload entrance should sit in the bottom-left corner')
})

test('collection managers can see and use fixed-grid upload controls', () => {
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  assert(wxml.includes('{{(canContribute || canManageImages) && !fixedGridPureMode}}'), 'fixed image-grid upload button should be visible in upload mode')
  assert(wxml.includes('seriesLevel < 3 && (canContribute || canManageImages) && !fixedGridPureMode'), 'subset upload button should be visible in upload mode')
  assert(wxml.includes('{{(canContribute || canManageImages) && !fixedGridPureMode}}" class="card-upload-btn"'), 'card upload button should be visible in upload mode')
  assert(wxml.includes('slot.type === \'upload\' && !fixedGridPureMode'), 'print-run upload slots should be hidden in pure image mode')
  assert(wxml.includes("slot.type === 'gap' && !fixedGridPureMode"), 'print-run gap placeholders should be hidden in pure image mode')
  assert(wxml.includes("slot.type === 'collapse' && !fixedGridPureMode"), 'print-run collapse placeholders should be hidden in pure image mode')
  assert(!wxml.includes('(isFixedImageGrid || isFixedCardSlots) && (canContribute || canManageImages)}}" class="action-btn action-btn-upload"'), 'non-free fixed-grid collections should not show a top-level upload button')
  assert(js.includes('if (canContribute || canManageSeries) return true'), 'upload permission guard should allow series managers')
})

test('collection detail keeps search and pure/upload display controls', () => {
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const wxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  const numberDisplay = read('miniprogram-card/pages/collection-series/numberDisplay.wxs')
  assert(wxml.includes('bindtap="toggleCardSearch"'), 'collection detail should render card search entry')
  assert(wxml.includes('series-card-search-input'), 'collection detail should render search input when opened')
  assert(wxml.includes('<view class="action-btn action-btn-view" bindtap="toggleFixedGridPureMode">{{fixedGridPureMode ? \'上传模式\' : \'纯图模式\'}}</view>'), 'all collections should toggle between pure image and upload modes')
  assert(wxml.includes('wx:if="{{(!fixedGridPureMode || card._gridImage) && !card._filterHidden}}"'), 'pure image mode should hide empty upload placeholders and respect search')
  assert(wxml.includes('lazy-load="{{true}}"'), 'collection list images should lazy-load')
  assert(wxml.includes("class=\"subset-count-badge {{card._isComplete ? 'complete' : ''}}\""), 'card progress should use a unified badge style')
  assert(wxss.includes('.subset-count-badge.complete'), 'complete card progress badge should have explicit styling')
  assert(wxml.includes('wx:if="{{!isFreeMode && checklistGroups.length > 0}}" class="action-btn action-btn-search"'), 'fixed collections should also expose search')
  assert(wxml.indexOf('bindtap="deleteSeries"') < wxml.indexOf('bindtap="toggleCardSearch"'), 'search entry should be the last action after destructive actions')
  assert(!wxml.includes('class="card-edit-btn" data-idx="{{card._idx}}" catchtap="onRenameCardTap">卡种'), 'card rows should not render a standalone card-kind edit button')
  assert(!wxml.includes('fixed-grid-complete-label'), 'fixed-grid thumbnails should not render completion checkmarks')
  assert(wxml.includes('seriesLevel >= 3 && canAddSubset && !checklistComplete'), 'complete checklists should not render the add-card-kind action')
  assert(wxml.includes('wx:for="{{visibleFreeImages}}"'), 'free image collections should render a paged image list')
  assert(wxml.includes('class="free-load-more"'), 'free image collections should expose pagination when needed')
  assert(wxml.includes('class="detail-desc-text" user-select="{{true}}"'), 'long detail description text should be selectable')
  assert(wxml.includes('class="row-text" user-select="{{true}}"'), 'long card titles should be selectable')
  assert(js.includes('_imageLabelDefaultYear: this._getImageLabelDefaultYear(series, defaultInfoEnabled)'), 'image labels should use series-level year fallback for duplicate suppression')
  assert(js.includes('_buildGroups(checklist, series)'), 'initial collection load should build checklist groups with the freshly computed series metadata')
  assert(js.includes('_buildGroups(cl, series)'), 'checklist updates should rebuild groups with the freshly computed series metadata')
  assert(js.includes('_buildGroups(checklist, seriesContext = this.data.series || {})'), 'group builder should accept an explicit series context instead of only reading stale page data')
  assert(wxml.includes('series._imageLabelDefaultYear'), 'image meta labels should compare against the effective series year')
  assert(numberDisplay.includes('function seasonKey'), 'image meta label matching should normalize season year formats')
  assert(!numberDisplay.includes('.match(/'), 'WXS should avoid regex literals because the mini program compiler rejects them')
  const numberSandbox = { module: { exports: {} } }
  vm.runInNewContext(numberDisplay, numberSandbox)
  assert.strictEqual(numberSandbox.module.exports.metaLabel('', '1997-98', '红宝', '1997-1998', '', 0, '', true), '红宝', 'same season labels should not repeat the series year')
  assert.strictEqual(numberSandbox.module.exports.metaLabel('', '1998-99', '红宝', '1997-1998', '', 0, '', true), '1998-99 · 红宝', 'different season labels should still show the image year')
  const progress = require('../miniprogram-card/utils/collectionProgress')
  const slots = progress.buildPrintRunSlots({
    text: 'Avery Johnson',
    completionTarget: 2,
    images: [{ url: 'red.jpg', year: '1997-98', cardKind: '红宝' }]
  }, {}, { imageLabelDefaults: { defaultYear: '1997-1998', defaultInfoEnabled: true } })
  const firstImageSlot = slots.find(slot => slot.type === 'image')
  assert.strictEqual(firstImageSlot.displayLabel, '红宝', 'progress-slot image labels should also suppress the series default year')
})

test('pure image collections show the top upload action', () => {
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  assert(wxml.includes('wx:if="{{isFreeMode && (canContribute || canManageSeries) && !fixedGridPureMode}}" class="action-btn action-btn-upload" bindtap="topBarUpload">上传图片</view>'), 'pure image collections need a top-level upload button in upload mode')
  assert(wxml.includes('wx:if="{{subsetType && (canContribute || canManageImages) && !fixedGridPureMode}}" class="empty-upload-btn"'), 'empty-state upload buttons should also be hidden in pure image mode')
  assert(!wxml.includes('wx:if="{{(isFixedImageGrid || isFixedCardSlots) && (canContribute || canManageSeries)}}" class="action-btn action-btn-upload"'), 'fixed card/slot collections should not get a top-level upload button')
})

test('collection card detail shows every image from the same card slot', () => {
  const js = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  const wxml = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxml')
  const wxss = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxss')
  assert(js.includes('imageSlides: []'), 'detail page should track a carousel slide list')
  assert(js.includes('_isFixedSlotSeries(series = {})'), 'detail page should identify fixed-slot series')
  assert(js.includes('_getDetailImageGroup(series = {}, item = {}, images = [], selected = {})'), 'detail page should choose the right image group')
  assert(js.includes('if (this._isFixedSlotSeries(series)) return list'), 'fixed slots should keep grouping by card slot')
  assert(js.includes('const selectedNumber = this._getDetailGroupNumber(selected, item)'), 'ordinary limited cards should group by selected number')
  assert(js.includes('this._getDetailGroupNumber(img, item) === selectedNumber'), 'ordinary limited cards should only include the same number')
  assert(js.includes('const groupedImages = this._getDetailImageGroup(series, found.item, found.images, found.image)'), 'loaded collection detail should compute grouped images')
  assert(js.includes('_buildImageSlides(images = [], selected = {})'), 'detail page should build slides from card-slot images')
  assert(js.includes('return { item: { ...item, subset: item.subset || doc.subset }, image: img, images }'), 'subset image lookup should keep all images in the same slot')
  assert(js.includes('return { item, image: img, images }'), 'checklist image lookup should keep all images in the same slot')
  assert(js.includes('imageSlides: this._buildImageSlides(groupedImages, found.image)'), 'loaded collection detail should show grouped images')
  assert(js.includes('this.data.imageSlides.map(slide => slide.url)'), 'preview should include all carousel images')
  assert(wxml.includes('indicator-dots="{{imageSlides.length > 1}}"'), 'carousel should indicate multiple same-slot images')
  assert(wxml.includes('wx:for="{{imageSlides}}"'), 'detail hero should render all same-slot slides')
  assert(wxml.includes('class="image-slide-count"'), 'detail hero should show a visible image count')
  assert(wxss.includes('.image-slide-count'), 'image count badge should be styled')
})

test('collection series chooses a concrete image before editing grouped fixed-slot images', () => {
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const wxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  assert(wxml.includes('data-grouped="1"'), 'fixed-grid representative image controls should mark grouped image actions')
  assert(wxml.includes('wx:if="{{showImageChoiceModal}}"'), 'grouped image actions need a chooser modal')
  assert(wxml.includes('wx:for="{{imageChoiceItems}}"'), 'chooser should render every candidate image')
  assert(wxml.includes('bindtap="onImageChoiceSelect"'), 'chooser items should select the concrete target image')
  assert(wxml.includes('catchtap="previewImageChoice"'), 'tapping chooser thumbnails should preview instead of selecting')
  assert(wxml.includes('data-url="{{item.url}}"'), 'chooser thumbnail preview should know the tapped image url')
  assert(js.includes('showImageChoiceModal: false'), 'page state should track chooser visibility')
  assert(js.includes('_openChecklistImageChoice(idx, action, fallbackImgIdx = 0, choiceNumber = \'\')'), 'grouped actions should open a checklist image chooser')
  assert(js.includes('_runChecklistImageChoice(action, idx, imgIdx, choiceNumber = \'\')'), 'selected image should be routed to edit or delete')
  assert(js.includes("this._openChecklistImageChoice(idx, 'delete', imgIdx, choiceNumber)"), 'grouped delete should choose the target image first')
  assert(js.includes("this._openChecklistImageChoice(idx, 'edit', imgIdx, choiceNumber)"), 'grouped edit should choose the target image first')
  assert(js.includes('previewImageChoice(e)'), 'chooser should support image preview')
  assert(js.includes('wx.previewImage({ current, urls: urls.length ? urls : [current] })'), 'chooser preview should include all candidate images')
  assert(js.includes('imageChoiceAction'), 'chooser should remember whether the action is edit or delete')
  assert(wxss.includes('.image-choice-item'), 'chooser needs explicit item styling')
})

test('collection series supports manager-only primary images', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const detailJs = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  const detailWxml = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxml')
  const detailWxss = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxss')
  assert(seriesWxml.includes('wx:if="{{canManageSeries && !isFreeMode}}"'), 'upload primary switch should only be visible to series managers')
  assert(seriesWxml.includes('bindchange="onUploadItemPrimary"'), 'upload modal should toggle primary state')
  assert(seriesWxml.includes('wx:if="{{canManageSeries && !editImageIsFree}}"'), 'edit modal primary switch should only be visible to series managers')
  assert(seriesWxml.includes('bindchange="onEditImagePrimary"'), 'edit modal should toggle primary state')
  assert(seriesJs.includes('isPrimary: false'), 'upload items should default primary switch off')
  assert(seriesJs.includes('isPrimary: !!img.isPrimary'), 'image normalization should preserve primary state')
  assert(seriesJs.includes('_markPrimaryImageInList(images, targetImageId = \'\')'), 'saving should normalize primary images to one item')
  assert(seriesJs.includes('const explicitPrimary = newImages.find(img => img.isPrimary)'), 'upload should respect manager-selected primary image')
  assert(seriesJs.includes('const images = this._markPrimaryImageInList([...this._normalizeImages(checklist[uploadIdx].images), ...newImages], explicitPrimary && explicitPrimary.imageId)'), 'upload should default to latest image when no explicit primary is selected')
  assert(seriesJs.includes('const primaryImage = images.find(img => img && img.isPrimary && !img.isSupplemental) || images.find(img => img && img.isPrimary)'), 'fixed grid should prefer explicit primary image')
  assert(seriesJs.includes('const latestImage = [...sourceImages].reverse().find(img => img && !img.isSupplemental) || [...sourceImages].reverse().find(Boolean)'), 'fixed grid should default to latest uploaded image')
  assert(seriesJs.includes('editImageIsPrimary: !!img.isPrimary'), 'edit modal should reflect current primary state')
  assert(seriesJs.includes('onEditImagePrimary(e) { this.setData({ editImageIsPrimary: !!e.detail.value }) }'), 'edit modal should save primary switch changes')
  assert(detailJs.includes('isPrimary: !!img.isPrimary'), 'detail page should preserve primary state')
  assert(detailJs.includes('isPrimary: !!img.isPrimary'), 'detail slides should know primary state')
  assert(detailWxml.includes('wx:if="{{item.isPrimary}}" class="primary-image-badge"'), 'detail page should show primary badge on primary slides')
  assert(detailWxss.includes('.primary-image-badge'), 'primary badge should be styled')
})

test('collection card detail omits face labels and only badges primary front images', () => {
  const detailJs = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  const detailWxml = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxml')
  const start = detailJs.indexOf('_buildImageSlides(images = [], selected = {})')
  const end = detailJs.indexOf('\n  _findImage', start)
  const body = detailJs.slice(start, end)
  assert(start >= 0 && end > start, 'missing image slide builder')
  assert(body.includes('badgeLabel: prefix'), 'detail slide labels should only keep the image count prefix')
  assert(!body.includes("'正面'"), 'detail slides should not label front images')
  assert(!body.includes("'背面'"), 'detail slides should not label back images')
  assert(body.includes('isPrimary: false'), 'back slides should not inherit the primary badge')
  assert(detailWxml.includes('imageSlides.length > 1 && item.badgeLabel'), 'empty slide labels should not render a blank badge')
})

test('print-run collection view groups same-number images under one primary tile', () => {
  const progress = require('../miniprogram-card/utils/collectionProgress')
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const withPrimary = progress.buildPrintRunSlots({
    text: 'Ray Allen /18',
    images: [
      { imageId: 'old', url: 'old.jpg', number: '11/18' },
      { imageId: 'primary', url: 'primary.jpg', number: '11/18', isPrimary: true },
      { imageId: 'latest', url: 'latest.jpg', number: '11/18' }
    ]
  }).filter(slot => slot.type === 'image' && slot.serial === '11')
  assert.strictEqual(withPrimary.length, 1, 'same serial should render one image tile')
  assert.strictEqual(withPrimary[0].image.url, 'primary.jpg', 'explicit primary should be the representative tile')
  assert.strictEqual(withPrimary[0].imageCount, 3, 'representative tile should know how many same-number images it covers')

  const withoutPrimary = progress.buildPrintRunSlots({
    text: 'Ray Allen /18',
    images: [
      { imageId: 'old', url: 'old.jpg', number: '11/18' },
      { imageId: 'latest', url: 'latest.jpg', number: '11/18' }
    ]
  }).filter(slot => slot.type === 'image' && slot.serial === '11')
  assert.strictEqual(withoutPrimary[0].image.url, 'latest.jpg', 'latest uploaded image should be the representative when no primary exists')
  assert(wxml.includes('slot.imageCount > 1 ? 1 : 0'), 'grouped print-run tiles should open the concrete image chooser')
  assert(wxml.includes('data-choice-number="{{slot.displayLabel}}"'), 'print-run image chooser should be scoped to the same number')
  assert(js.includes('const choiceNumber = e.currentTarget.dataset.choiceNumber || \'\''), 'edit/delete handlers should read the number scope')
})

test('completion-target collection view groups same-number images under one primary tile', () => {
  const progress = require('../miniprogram-card/utils/collectionProgress')
  const slots = progress.buildPrintRunSlots({
    text: 'Ray Allen',
    completionTarget: 18,
    images: [
      { imageId: 'old', url: 'old.jpg', number: '11/18' },
      { imageId: 'primary', url: 'primary.jpg', number: '11/18', isPrimary: true },
      { imageId: 'latest', url: 'latest.jpg', number: '11/18' }
    ]
  })
  const imageSlots = slots.filter(slot => slot.type === 'image')
  assert.strictEqual(imageSlots.length, 1, 'same number should render one image tile even when only completionTarget is set')
  assert.strictEqual(imageSlots[0].serial, '11')
  assert.strictEqual(imageSlots[0].displayLabel, '11/18')
  assert.strictEqual(imageSlots[0].image.url, 'primary.jpg', 'explicit primary should be the representative tile')
  assert.strictEqual(imageSlots[0].imageCount, 3, 'representative tile should know how many same-number images it covers')
  assert.strictEqual(progress.getItemCollectedCount({
    text: 'Ray Allen',
    completionTarget: 18,
    images: [
      { imageId: 'old', url: 'old.jpg', number: '11/18' },
      { imageId: 'latest', url: 'latest.jpg', number: '11/18' }
    ]
  }), 1, 'same number should count as one collected card')
})

test('checklist item completion target can be disabled', () => {
  const progress = require('../miniprogram-card/utils/collectionProgress')
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const seriesOps = read('miniprogram-card/cloudfunctions/seriesOps/index.js')
  const adminOps = read('miniprogram-card/cloudfunctions/adminOps/index.js')
  const item = {
    text: 'Ray Allen /18',
    completionTarget: 0,
    images: [{ imageId: 'img', url: 'img.jpg', number: '11/18' }]
  }
  assert.strictEqual(progress.getCompletionTarget(item), 0, 'explicit zero target should disable progress')
  assert.deepStrictEqual(progress.buildPrintRunSlots(item), [], 'disabled targets should not generate empty slots')
  const stats = progress.buildChecklistProgressStats([item])
  assert.strictEqual(stats.totalCards, 0, 'disabled targets should not count toward checklist total')
  assert.strictEqual(stats.withImages, 0, 'disabled targets should not show a complete progress icon')
  assert.strictEqual(stats.listImageCount, 1, 'disabled targets should still preserve actual images')
  assert(seriesWxml.includes('无需补图目标'), 'edit modal should expose the no-target option')
  assert(seriesJs.includes('editCardNoCompletionTarget'), 'page state should track no-target mode')
  assert(seriesJs.includes('? 0'), 'saving no-target mode should persist zero target')
  assert(seriesOps.includes('else if (target === 0) next.completionTarget = 0'), 'series cloud function should allow clearing target')
  assert(adminOps.includes('else if (target === 0) next.completionTarget = 0'), 'admin cloud function should allow clearing target')
})

test('free series completion target can be disabled', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  assert(seriesWxml.includes('无需完成目标'), 'series manage modal should expose a no-target option')
  assert(seriesWxml.includes('editSeriesNoCompletionTarget'), 'series manage modal should bind no-target state')
  assert(seriesJs.includes('editSeriesNoCompletionTarget'), 'page state should track free-series no-target mode')
  assert(seriesJs.includes('if (rawTarget === 0) target = 0'), 'free-series stats should not fall back when target is explicitly zero')
  assert(seriesJs.includes('const target = editSeriesNoCompletionTarget ? 0'), 'saving free-series no-target mode should persist zero target')
  assert(seriesJs.includes('saveSeriesCompletionTarget({ auto: true })'), 'no-target switch should auto-save after toggling')
  assert(seriesJs.includes('editSeriesLastCompletionTarget'), 'page state should remember the last positive target when toggling back on')
})

test('series image uploads require a mutable globally unique public uploader id', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const detailJs = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  const detailWxml = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.wxml')
  const cloudJs = read('miniprogram-card/cloudfunctions/seriesOps/index.js')
  const dataJs = read('miniprogram-card/utils/collectionData.js')
  const myCollectionJs = read('miniprogram-card/pages/my-collection/my-collection.js')
  const myCollectionWxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  assert(seriesJs.includes('publicUserIdLocked: false'), 'collection page should treat public uploader id as editable')
  assert(seriesJs.includes('async _loadPublicUserProfile()'), 'collection page should refresh an existing public id after it is set elsewhere')
  assert(seriesJs.includes('onShow()'), 'collection page should reload public id when returning to the page')
  assert(seriesJs.includes('await this._loadPublicUserProfile().catch'), 'image editor should wait for existing public id before editing uploader metadata')
  assert(seriesJs.includes('_ensureUploadPublicUserId'), 'upload should validate/set public id before any series image submission')
  assert(seriesJs.includes('uploaderPublicId'), 'uploaded images should store public uploader id snapshots')
  assert(seriesJs.includes('uploaderPublicId: uploaderPublicId || this.data.publicUserId ||'), 'uploaded images should store uploader id regardless of image source')
  assert(seriesWxml.includes('上传用户 ID'), 'upload modal should ask for public uploader id')
  assert(seriesWxml.includes('<view wx:if="{{!publicUserId}}" class="form-row-inline">'), 'upload modal should hide the public id input once an id exists')
  assert(seriesWxml.includes('editImageCanEdit && !editImageUploaderPublicId && !publicUserId'), 'edit image modal should hide the public id input once an id exists')
  assert(seriesWxml.includes('该 ID 会在卡片详情公开展示'), 'upload modal should disclose public visibility')
  assert(!seriesWxml.includes('可修改但需要全站唯一'), 'upload modal should not expose internal uniqueness rules in helper text')
  assert(!seriesWxml.includes('不能包含违禁内容'), 'upload modal should not expose content safety rules in helper text')
  assert(detailWxml.includes('上传用户'), 'collection card detail should expose uploader as its own field')
  assert(detailJs.includes("user_photo: '用户实拍'"), 'detail page should keep user-photo source wording as 用户实拍')
  assert(!detailJs.includes("return '用户上传'"), 'detail page should not invent a 用户上传 source label')
  assert(myCollectionJs.includes('showPublicIdModal'), 'my collection home should provide a public id entry modal')
  assert(myCollectionJs.includes('savePublicUserId'), 'my collection home should allow setting public id')
  assert(myCollectionJs.includes('getPublicUserIdErrorMessage'), 'my collection home should show specific public id errors')
  assert(myCollectionWxml.includes('用户 ID'), 'my collection home should expose the public id entry')
  assert(!myCollectionWxml.includes('用户 ID 可修改'), 'my collection public id modal should omit the extra editability hint')
  assert(detailJs.includes('buildUploaderDisplay'), 'detail page should display uploader id separately from source')
  assert(detailJs.includes('return publicId'), 'detail page should show uploader id without a fixed prefix')
  assert(cloudJs.includes("db.collection('user_public_profiles')"), 'cloud function should persist public user profiles')
  assert(cloudJs.includes('sanitizePublicUserId'), 'cloud function should sanitize public ids')
  assert(cloudJs.includes('security.msgSecCheck'), 'cloud function should check public id content safety')
  assert(cloudJs.includes('publicIdKey'), 'cloud function should enforce normalized global uniqueness')
  assert(cloudJs.includes('syncPublicUserIdSnapshots'), 'cloud function should update existing public id snapshots after rename')
  assert(dataJs.includes('getPublicUserProfile'), 'client data layer should expose public profile fetch')
  assert(dataJs.includes('setPublicUserId'), 'client data layer should expose public id setup')
  assert(dataJs.includes('getPublicUserIdErrorMessage'), 'client data layer should map public id errors to user-facing reasons')
})

test('series upload owned flow can capture purchase and grading details', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const uploadOwnedStart = seriesWxml.indexOf('<view wx:if="{{item.owned}}" class="upload-owned-fields">')
  const uploadOwnedEnd = seriesWxml.indexOf('<view class="form-row-inline">\n              <text class="form-label-sm">来源</text>', uploadOwnedStart)
  const uploadOwnedBlock = seriesWxml.slice(uploadOwnedStart, uploadOwnedEnd)
  assert(uploadOwnedStart >= 0 && uploadOwnedEnd > uploadOwnedStart, 'upload owned fields block should be present')
  assert(seriesJs.includes('UPLOAD_GRADE_OPTIONS'), 'upload flow should expose grade choices')
  assert(seriesJs.includes('onUploadItemLedgerInput'), 'upload owned fields should update purchase form state')
  assert(seriesJs.includes('onUploadItemGradingCompanyChange'), 'upload owned fields should support grading company selection')
  assert(seriesJs.includes('_createLedgerForOwnedUploads'), 'owned uploads should create private collection ledger entries')
  assert(seriesJs.includes('this._buildHoldLedgerPayload(newImage.url, item, uploadItem, newImage)'), 'ledger creation should use the uploaded image metadata')
  assert(seriesJs.includes('cardVariant: base.cardVariant'), 'direct upload should initialize card variant from image defaults')
  assert(seriesJs.includes("cardVariant: String(item.cardVariant || '').trim().slice(0, 80)"), 'direct upload should persist card variant on the uploaded image')
  assert(uploadOwnedBlock.includes('class="form-group-modal"'), 'owned upload form should use the same vertical field style as long-press hold')
  assert(uploadOwnedBlock.includes('class="hold-ledger-grid"'), 'owned upload form should use the same two-column grid as long-press hold')
  assert(uploadOwnedBlock.includes('class="form-input-modal"'), 'owned upload form inputs should match long-press hold inputs')
  assert(uploadOwnedBlock.includes('form-input-modal form-picker-modal'), 'owned upload form pickers should match long-press hold pickers')
  assert(uploadOwnedBlock.includes('买入成本'), 'owned upload form should show purchase cost')
  assert(uploadOwnedBlock.includes('data-field="quantity"'), 'owned upload form should capture quantity like long-press hold')
  assert(uploadOwnedBlock.includes('value="{{item.cardVariant}}" data-i="{{index}}" data-field="cardVariant"'), 'owned upload form should capture card variant')
  assert(seriesWxml.includes('如 2017 总决赛、2018 总决赛'), 'owned upload form should use the same card variant example as long-press hold')
  assert(uploadOwnedBlock.includes('评级公司'), 'owned upload form should show grading company')
  assert(seriesWxml.includes('评级分数'), 'owned upload form should show grade selector')
  assert(seriesJs.includes('AUTHENTIC / 鉴真'), 'grade selector should include authentic-only grading')
})

test('long-press hold ledger can capture card variant', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  assert(seriesWxml.includes('data-field="cardVariant"'), 'long-press hold modal should expose card variant input')
  assert(seriesWxml.includes('如 2017 总决赛、2018 总决赛'), 'card variant input should use the same example copy as my cards')
  assert(seriesJs.includes("cardVariant: payload.cardVariant || ''"), 'hold modal should initialize card variant from the selected image')
  assert(seriesJs.includes("cardVariant: String(form.cardVariant || img.cardVariant || '').trim().slice(0, 80)"), 'hold ledger payload should persist user-entered card variant')
})

test('grading can be cleared and back image removal uses corner icons', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const seriesWxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  const myJs = read('miniprogram-card/pages/my-collection/my-collection.js')
  const myWxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const myWxss = read('miniprogram-card/pages/my-collection/my-collection.wxss')
  assert(seriesJs.includes("const HOLD_GRADING_OPTIONS = ['未评级'"), 'holding flow should allow clearing grading company')
  assert(seriesJs.includes('HOLD_GRADE_OPTIONS'), 'holding flow should provide grade selector options')
  assert(seriesJs.includes('AUTHENTIC / 鉴真'), 'holding flow should support authentic-only grade')
  assert(myJs.includes("const GRADING_OPTIONS = ['未评级'"), 'my collection should allow clearing grading company')
  assert(myJs.includes('GRADE_OPTIONS'), 'my collection should provide grade selector options')
  assert(myWxml.includes('bindchange="onGradeChange"'), 'my collection grade should use a picker')
  assert(seriesWxml.includes('upload-back-remove-icon'), 'series upload/edit should remove back image from a corner icon')
  assert(myWxml.includes('image-remove-corner'), 'my collection should remove back image from a corner icon')
  assert(seriesWxss.includes('.upload-back-remove-icon'), 'series corner remove icon should be styled')
  assert(myWxss.includes('.image-remove-corner'), 'my collection corner remove icon should be styled')
  assert(!seriesWxml.includes('>移除背面</text>'), 'series upload/edit should not show remove back as text button')
  assert(!myWxml.includes('移除背面'), 'my collection should not show remove back as a text button')
})

test('fixed slots center uploaded images without empty metadata below', () => {
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const wxss = read('miniprogram-card/pages/collection-series/collection-series.wxss')
  assert(wxml.includes('!card._gridImage'), 'fixed grid metadata should only render for empty slots')
  assert(wxss.includes('.fixed-grid-image-wrap { display: flex; align-items: center; justify-content: center; }'), 'fixed grid images should be centered')
  assert(wxss.includes('.fixed-grid-card.has-image'), 'fixed grid image cards should avoid blank bottom spacing')
})

test('collection series shows personal owned progress only when owned cards exist', () => {
  const js = read('miniprogram-card/pages/collection-series/collection-series.js')
  const wxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  assert(js.includes('_buildMyOwnedProgressFromChecklist'))
  assert(js.includes('_buildMyOwnedProgressFromFreeImages'))
  assert(js.includes('showMyOwnedProgress: count > 0'))
  assert(js.includes('myOwnedProgressText: `${count}/${total}`'))
  assert(js.includes('myOwnedProgressPercent: total > 0 ? Math.round(count / total * 100) : 0'))
  assert(wxml.includes('wx:if="{{showMyOwnedProgress}}"'))
  assert(wxml.includes("我的拥有进度{{myOwnedProgressText ? ' ' + myOwnedProgressText : ''}}"))
  assert(wxml.includes('width: {{myOwnedProgressPercent}}%;'))
  assert(wxml.includes('我的拥有进度'))
})

test('my collection supports card export copy, single-year suggestions and series grouping', () => {
  const js = read('miniprogram-card/pages/my-collection/my-collection.js')
  const wxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const wxss = read('miniprogram-card/pages/my-collection/my-collection.wxss')
  const appJson = read('miniprogram-card/app.json')
  assert(js.includes('function buildMyCollectionYearOptions'))
  assert(js.includes('generated.push(String(year))'))
  assert(js.includes('function buildSeriesCostGroups'))
  assert(js.includes('const CARD_SORT_OPTIONS'))
  assert(js.includes('const SERIES_SORT_OPTIONS'))
  assert(js.includes("value: 'seriesTotalCost', label: '总买入'"))
  assert(js.includes("value: 'seriesHoldingCost', label: '持有成本'"))
  assert(js.includes("value: 'seriesSaleAmount', label: '卖出金额'"))
  assert(js.includes("value: 'seriesProfitAmount', label: '盈亏'"))
  assert(js.includes("value: 'seriesQuantity', label: '卡片数量'"))
  assert(js.includes("value: 'seriesLatestTime', label: '最近更新'"))
  assert(js.includes('function getSeriesSortValue'))
  assert(js.includes('seriesGroups: buildSeriesCostGroups(ledger, this.data.moneyVisible, itemMoneyVisibleMap, this.data.sortKey, this.data.sortOrder)'))
  assert(js.includes('moneyVisibilityKey: `series:${key}`'))
  assert(js.includes('moneyVisibleForItem: !!(moneyVisible || itemMoneyVisibleMap[group.moneyVisibilityKey])'))
  assert(js.includes('openSeriesGroupDetail'))
  assert(js.includes('/pages/my-collection-series-detail/my-collection-series-detail?'))
  assert(wxml.includes('如 2008 或 2016-17'))
  assert(wxml.includes('导出卡片'))
  assert(wxml.includes('按图鉴'))
  assert(wxml.includes('总花费'))
  assert(wxml.includes('{{sortOrderLabel}}'))
  assert(wxml.includes('bindtap="openSeriesGroupDetail"'))
  assert(wxml.includes('data-id="{{item.moneyVisibilityKey}}" catchtap="toggleItemMoneyVisible"'))
  assert(wxml.includes("item.moneyVisibleForItem ? '总花费 ¥' + item.totalCostText : '总花费 ••••'"))
  assert(wxml.includes("item.moneyVisibleForItem ? '持有成本 ¥' + item.holdingCostText : '持有成本 ••••'"))
  assert(wxss.includes('.series-summary-card { position: relative;'))
  assert(appJson.includes('pages/my-collection-series-detail/my-collection-series-detail'))
})

test('my collection can collapse same-card average groups', () => {
  const js = read('miniprogram-card/pages/my-collection/my-collection.js')
  const wxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const wxss = read('miniprogram-card/pages/my-collection/my-collection.wxss')
  const rules = read('miniprogram-card/PRODUCT_RULES.md')
  assert(js.includes('function buildSameCardDisplayItems'), 'my collection should build same-card grouped display rows')
  assert(js.includes('expandedSameCardGroupMap'), 'same-card groups should keep explicit expanded state')
  assert(js.includes('const groupKey = item.identityKey'), 'same-card groups should reuse the average-price identity key')
  assert(js.includes("const moneyVisibilityKey = `same-card:${groupKey}`"), 'same-card groups should have their own money visibility key')
  assert(js.includes('toggleSameCardGroup'), 'same-card groups should expand and collapse')
  assert(js.includes('displayItems: buildSameCardDisplayItems('), 'card list should render grouped display items')
  assert(wxml.includes("item._displayType === 'sameCardGroup'"), 'card list should render a same-card group branch')
  assert(wxml.includes('bindtap="toggleSameCardGroup"'), 'same-card group header should be clickable')
  assert(wxml.includes('wx:for="{{item.children}}"'), 'expanded same-card groups should render child cards')
  assert(wxml.includes('same-card-group-badge'), 'same-card groups should label grouped rows')
  assert(wxss.includes('.same-card-group'), 'same-card group styles should exist')
  assert(wxss.includes('.same-card-children'), 'same-card children should be visually separated')
  assert(rules.includes('同类卡合并展示必须复用均价统计的同一个 `identityKey` 口径'), 'product rules should document same-card grouping scope')
})

test('my collection visually distinguishes sold cards beyond the status badge', () => {
  const wxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const wxss = read('miniprogram-card/pages/my-collection/my-collection.wxss')
  assert(wxml.includes('class="card-item status-{{item.statusClass}}"'), 'normal card rows should carry status classes')
  assert(wxml.includes('class="card-item same-card-child status-{{child.statusClass}}"'), 'expanded same-card child rows should carry status classes')
  assert(wxml.includes('class="same-card-group status-{{item.statusClass}}"'), 'same-card groups should carry status classes')
  assert(wxss.includes('.card-item.status-sold'), 'sold card rows should have dedicated styling')
  assert(wxss.includes('background: #eef0f3'), 'sold card rows should use a neutral gray background')
  assert(!wxss.includes('.card-item.status-sold::before'), 'sold card rows should not use a left-side marker')
  assert(wxss.includes('.same-card-group.status-sold'), 'all-sold same-card groups should have dedicated styling')
})

test('my collection hides default status and condition badges', () => {
  const js = read('miniprogram-card/pages/my-collection/my-collection.js')
  const wxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const detailJs = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.js')
  const detailWxml = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.wxml')
  assert(js.includes("conditionLabel: condition === '通行' ? '' : condition"), 'only default 通行 condition should hide its badge')
  assert(js.includes("showStatusBadge: status !== 'holding'"), 'default 持有中 status should not render a badge')
  assert(js.includes("showStatusBadge: groupStatus !== 'holding'"), 'same-card holding groups should not render a status badge')
  assert(wxml.includes("item.showStatusBadge && item.status === 'sold'"), 'sold badge should render in the title row')
  assert(wxml.includes("item.showStatusBadge && item.status !== 'sold'"), 'non-sold non-default badges should stay in metadata')
  assert(wxml.includes("item.status === 'sold' && item.moneyVisibleForItem"), 'sold sale/profit row should only show when money is visible')
  assert(wxml.includes("child.status === 'sold' && child.moneyVisibleForItem"), 'expanded sold child sale/profit row should only show when money is visible')
  assert(detailJs.includes("conditionLabel: condition === '通行' ? '' : condition"), 'series detail should hide only default 通行 condition badge')
  assert(detailJs.includes("showStatusBadge: status !== 'holding'"), 'series detail should hide default 持有中 status badge')
  assert(detailWxml.includes('class="card-item status-{{item.statusClass}}"'), 'series detail card rows should carry status classes')
  assert(detailWxml.includes("item.showStatusBadge && item.status === 'sold'"), 'series detail sold badge should render in title row')
  assert(detailWxml.includes("item.status === 'sold' && item.moneyVisibleForItem"), 'series detail sold sale/profit row should only show when money is visible')
})

test('user card item condition is persisted by cloud normalization', () => {
  const seriesOps = read('miniprogram-card/cloudfunctions/seriesOps/index.js')
  const myCollection = read('miniprogram-card/pages/my-collection/my-collection.js')
  const seriesDetail = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.js')
  const collectionSeries = read('miniprogram-card/pages/collection-series/collection-series.js')
  const rules = read('miniprogram-card/PRODUCT_RULES.md')
  assert(myCollection.includes("const CONDITION_OPTIONS = ['通行', '瑕疵', '非原封']"), 'my collection should expose 非原封 as a condition option')
  assert(seriesDetail.includes("const CONDITION_OPTIONS = ['通行', '瑕疵', '非原封']"), 'series detail card editor should expose 非原封 as a condition option')
  assert(collectionSeries.includes("const CONDITION_OPTIONS = ['通行', '瑕疵', '非原封']"), 'series upload and long-press hold forms should expose 非原封 as a condition option')
  assert(seriesOps.includes("const USER_CARD_ITEM_CONDITION_VALUES = ['通行', '瑕疵', '非原封']"), 'cloud function should whitelist supported condition values')
  assert(seriesOps.includes('function normalizeUserCardItemCondition(condition)'), 'cloud function should normalize user card condition')
  assert(seriesOps.includes('condition: normalizeUserCardItemCondition(input.condition)'), 'cloud function should persist condition into user_card_items')
  assert(!myCollection.includes("{ value: 'non_sealed'"), '非原封 should not be modeled as a card feature')
  assert(!collectionSeries.includes("{ value: 'non_sealed'"), '非原封 should not be modeled as a series image feature')
  assert(rules.includes('默认品相是 `通行`，另有 `瑕疵` 和 `非原封` 分类。'), 'product rules should document the three supported condition values')
})

test('repurchase keeps series linkage and skips stale series image sync warnings', () => {
  const js = read('miniprogram-card/pages/my-collection/my-collection.js')
  const detailJs = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.js')
  ;[js, detailJs].forEach(source => {
    assert(source.includes('function buildRepurchaseSeriesLinkPatch(item = {})'), 'repurchase should share a focused series-link patch')
    assert(source.includes('seriesId: item.seriesId || \'\''), 'repurchase should preserve series id')
    assert(source.includes('seriesName: item.seriesName || \'\''), 'repurchase should preserve series name')
    assert(source.includes('itemId: item.itemId || \'\''), 'repurchase should preserve checklist item id')
    assert(source.includes('imageId: item.imageId || \'\''), 'repurchase should preserve linked image id')
    assert(source.includes('...buildRepurchaseSeriesLinkPatch(item)'), 'repurchase form should apply the series-link patch')
    assert(source.includes('function isMissingSeriesDocumentError(err)'), 'stale series sync should detect missing series documents')
    assert(source.includes('if (!isMissingSeriesDocumentError(err))'), 'missing series documents should not spam sync warnings')
  })
})

test('my collection series detail drills into grouped cards', () => {
  const js = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.js')
  const wxml = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.wxml')
  const json = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.json')
  assert(js.includes('filterItemsForSeriesGroup'))
  assert(js.includes('goSeriesDetail'))
  assert(js.includes('/pages/collection-series/collection-series?id='))
  assert(js.includes("groupTitle: '未关联图鉴'"))
  assert(js.includes('groupStats: this.buildStats(ledger)'))
  assert(wxml.includes('series-detail-header'))
  assert(wxml.includes('class="page series-detail-page"'))
  assert(wxml.includes('bindtap="goSeriesDetail"'))
  assert(wxml.includes('{{groupTitle}}'))
  assert(wxml.includes('{{groupStats.totalQuantity}}'))
  assert(wxml.includes('openCollectionCardDetail'))
  assert(wxml.includes('openEditModal'))
  assert(wxml.includes('openRepurchaseModal'))
  assert(!wxml.includes('openSameTypeModal'), 'series grouped cards should not show the redundant same-type add action')
  assert(!wxml.includes('同款新增'), 'series grouped cards should not show the redundant same-type add label')
  assert(wxml.includes('exportItemImage'))
  assert(wxml.includes('deleteItem'))
  const wxss = read('miniprogram-card/pages/my-collection-series-detail/my-collection-series-detail.wxss')
  assert(wxss.includes('.series-detail-page .toolbar { margin-bottom: 18rpx; }'))
  assert(wxss.includes('.series-detail-page .sort-bar { margin: 0 0 18rpx; }'))
  assert(wxss.includes('.series-detail-page .status-tab,'))
  assert(json.includes('图鉴卡片'))
})

test('my collection dashboard visualizes private ledger data', () => {
  const appJson = read('miniprogram-card/app.json')
  const homeJs = read('miniprogram-card/pages/my-collection/my-collection.js')
  const homeWxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const dashboardJs = read('miniprogram-card/pages/my-collection-dashboard/my-collection-dashboard.js')
  const dashboardWxml = read('miniprogram-card/pages/my-collection-dashboard/my-collection-dashboard.wxml')
  const dashboardWxss = read('miniprogram-card/pages/my-collection-dashboard/my-collection-dashboard.wxss')
  const dashboardJson = read('miniprogram-card/pages/my-collection-dashboard/my-collection-dashboard.json')
  const rules = read('miniprogram-card/PRODUCT_RULES.md')

  assert(appJson.includes('pages/my-collection-dashboard/my-collection-dashboard'), 'dashboard page should be registered')
  assert(homeJs.includes('openDashboard'), 'my collection should expose a dashboard navigation handler')
  assert(homeJs.includes('/pages/my-collection-dashboard/my-collection-dashboard'), 'dashboard entry should navigate to the private dashboard page')
  assert(homeWxml.includes('openDashboard'), 'my collection should render a dashboard entry')
  assert(homeWxml.includes('看板'), 'dashboard entry should be visible from my collection')
  assert(dashboardJson.includes('我的卡片看板'), 'dashboard page should use a dedicated navigation title')
  assert(dashboardJs.includes('function buildDashboardGroups'), 'dashboard should build reusable grouped chart data')
  assert(dashboardJs.includes("type: 'series'"), 'dashboard should support series share analysis')
  assert(dashboardJs.includes("type: 'player'"), 'dashboard should support player share analysis')
  assert(dashboardJs.includes("type: 'condition'"), 'dashboard should support condition distribution')
  assert(dashboardJs.includes("type: 'status'"), 'dashboard should support status distribution')
  assert(dashboardJs.includes('activeMetric'), 'dashboard should switch between cost and quantity views')
  assert(dashboardJs.includes('function buildDashboardViewState'), 'dashboard metric changes should build the next view state before setData')
  assert(dashboardJs.includes('refreshDashboard({ activeMetric: metric })'), 'dashboard metric changes should avoid showing stale chart data between states')
  assert(dashboardJs.includes('openDashboardDetail'), 'dashboard rows should drill into detail lists')
  assert(!dashboardJs.includes('openTopDashboardDetail'), 'dashboard chart visual area should not carry a low-value largest-category shortcut')
  assert(dashboardJs.includes('selectedDashboardKey'), 'dashboard should keep a visible selected category state')
  assert(dashboardJs.includes('function getPieCanvasSize'), 'dashboard pie canvas should convert rpx size to device px to avoid clipped charts')
  assert(dashboardJs.includes('function buildSeriesEfficiencyRows'), 'dashboard should expose collection investment efficiency insights')
  assert(!dashboardJs.includes("'已收'"), 'series investment rows should not show low-value collected labels for no-target series')
  assert(dashboardJs.includes('function isLinkedSeriesItem'), 'dashboard should distinguish linked series items from unlinked ledger cards')
  assert(dashboardJs.includes("card.type === 'series' ? filterLinkedSeriesItems(items) : items"), 'series share charts should exclude unlinked cards')
  assert(dashboardJs.includes('const linkedSeriesItems = filterLinkedSeriesItems(items)'), 'series investment and concentration should use only linked series cards')
  assert(dashboardJs.includes("const seriesRows = buildCostMap(linkedSeriesItems, 'series')"), 'series concentration should exclude unlinked cards')
  assert(dashboardJs.includes('const seriesTotalCost = linkedSeriesItems.reduce'), 'series concentration percentages should be based on linked series cards only')
  assert(dashboardJs.includes('function buildMonthlyTrendRows'), 'dashboard should expose purchase trend insights')
  assert(dashboardJs.includes('function buildConcentrationSummary'), 'dashboard should expose concentration risk insights')
  assert(dashboardJs.includes('function buildSameCardInsights'), 'dashboard should expose same-card average price insights')
  assert(dashboardJs.includes('function buildSameCardInsightTitle'), 'same-card insights should use a concise collector-facing title')
  assert(dashboardJs.includes("return printRun ? `${player} ${printRun}编` : player"), 'same-card insight title should show player plus print run only')
  assert(dashboardJs.includes('function buildSameCardInsightSubtitle'), 'same-card insights should keep brand and series context')
  assert(dashboardJs.includes('return [item.year, item.brand, item.cardSeries]'), 'same-card insight subtitle should show year, manufacturer and series without long card names')
  assert(dashboardJs.includes('cover: normalizeImageUrl(item.imageUrl)'), 'same-card insights should keep a representative cover image')
  assert(dashboardJs.includes('function buildTodoInsights'), 'dashboard should expose actionable private ledger reminders')
  assert(dashboardJs.includes('insightSectionsCollapsed'), 'dashboard should allow static insight sections to be collapsed')
  assert(dashboardJs.includes('toggleInsightSections'), 'dashboard should expose a static insight collapse handler')
  assert(!dashboardJs.includes("key: 'missing-series'"), 'dashboard reminders should not treat unlinked series as a pending task')
  assert(!dashboardJs.includes('待关联图鉴'), 'dashboard reminders should not prompt users to link cards that do not belong to curated series')
  assert(dashboardJs.includes('function buildDashboardIdentityKey'), 'dashboard should compute the same grouping key as my collection when old items do not persist it')
  assert(dashboardJs.includes('const key = getDashboardIdentityKey(item)'), 'same-card insights must use the dashboard identity key helper')
  assert(dashboardJs.includes('return cleanText(item.identityKey) || buildDashboardIdentityKey(item)'), 'same-card insights should prefer persisted identityKey and fall back to the same-card rule')
  assert(!dashboardJs.includes("'无目标'"), 'dashboard should not expose an ambiguous no-target label in insight rows')
  assert(dashboardWxml.includes('canvas-id="seriesPie"'), 'series chart should render as a pie canvas')
  assert(dashboardWxml.includes('canvas-id="playerPie"'), 'player chart should render as a pie canvas')
  assert(dashboardWxml.includes('dashboard-detail-list'), 'dashboard should render filtered card details')
  assert(dashboardWxml.includes('series-efficiency-list'), 'dashboard should render collection efficiency cards')
  assert(dashboardWxml.includes('wx:if="{{series.completionPercentText}}"'), 'series investment status should render only when a target percentage exists')
  assert(dashboardWxml.includes('monthly-trend-list'), 'dashboard should render monthly purchase trend rows')
  assert(dashboardWxml.includes('concentration-grid'), 'dashboard should render concentration summary cards')
  assert(dashboardWxml.includes('same-card-insights'), 'dashboard should render same-card average price insights')
  assert(dashboardWxml.includes('图鉴投入度'), 'series investment section should use positioning wording instead of efficiency wording')
  assert(!dashboardWxml.includes('图鉴投入效率'), 'series investment section should not imply efficiency evaluation')
  assert(dashboardWxml.indexOf('same-card-insights') < dashboardWxml.indexOf('series-efficiency-list'), 'series investment section should appear after same-card average insights')
  assert(dashboardWxml.includes('same-card-subtitle'), 'same-card average rows should keep manufacturer and series context')
  assert(dashboardWxml.includes('class="same-card-cover"'), 'same-card average rows should show a representative card image')
  assert(dashboardWxml.includes('todo-insights'), 'dashboard should render private ledger reminder cards')
  assert(dashboardWxml.includes('insight-collapse-bar'), 'dashboard should render one collapse control for metric-independent insight sections')
  assert(dashboardWxml.includes('wx:if="{{!insightSectionsCollapsed}}"'), 'dashboard should hide metric-independent insight sections when collapsed')
  assert(dashboardWxml.includes("{{insightSectionsCollapsed ? '展开' : '收起'}}"), 'dashboard collapse control should switch label between expand and collapse')
  assert(!dashboardWxml.includes('identityKey'), 'dashboard should not show implementation terms to users')
  assert(!dashboardWxml.includes('无目标'), 'dashboard should not show ambiguous no-target wording to users')
  assert(dashboardWxml.includes('toggleMoneyVisible'), 'dashboard should share the same money visibility behavior')
  assert(!dashboardWxml.includes('bindtap="openTopDashboardDetail"'), 'dashboard chart visual area should not expose the largest-category shortcut')
  assert(!dashboardWxml.includes('查看最大项'), 'dashboard chart visual area should not show a largest-category action label')
  assert(dashboardWxml.includes('selectedDashboardKey === row.detailKey'), 'dashboard ranking rows should show the selected category')
  assert(dashboardWxml.includes('chart-visual-row'), 'dashboard charts should keep the visual summary above ranking rows')
  assert(dashboardWxml.includes('chart-summary-value'), 'dashboard charts should show a compact top summary beside the chart')
  assert(!dashboardWxml.includes('row.recordCount}} 条'), 'dashboard ranking meta should only show card quantity, not record count')
  assert(dashboardWxml.includes('wx:if="{{activeMetric !== \'quantity\'}}"'), 'quantity charts should not duplicate quantity as the value meta')
  assert(dashboardWxss.includes('.dashboard-chart-card'), 'dashboard should have chart card styling')
  assert(dashboardWxss.includes('.dashboard-section-card'), 'dashboard insight sections should share card styling')
  assert(dashboardWxss.includes('.trend-bar'), 'dashboard purchase trends should use compact bar visuals')
  assert(dashboardWxss.includes('.todo-insight-card'), 'dashboard reminders should have explicit styling')
  assert(dashboardWxss.includes('.insight-collapse-bar'), 'dashboard collapse control should have explicit styling')
  assert(dashboardWxss.includes('.chart-body { display: flex; flex-direction: column;'), 'dashboard chart body should stack chart and ranking on mobile')
  assert(dashboardWxss.includes('.chart-row.active'), 'dashboard selected category should be visually highlighted')
  assert(dashboardWxss.includes('.dashboard-detail-card'), 'dashboard detail rows should have card styling')
  assert(rules.includes('我的卡片看板只分析私人台账数据'), 'product rules should keep dashboard private and scoped')
  assert(rules.includes('图鉴投入度、购买趋势、集中度、同款均价和待处理提醒'), 'product rules should document the dashboard insight modules')
  assert(!rules.includes('图鉴投入效率'), 'product rules should avoid efficiency wording for series investment')
  assert(rules.includes('图鉴相关维度不纳入未关联图鉴'), 'product rules should document that unlinked cards are excluded from series-specific dashboard views')
  assert(rules.includes('待处理提醒不把未关联图鉴作为待办'), 'product rules should document that missing series linkage is not a dashboard todo')
  assert(rules.includes('不随 `花费/数量` 维度切换的辅助分析模块，可以提供统一收起/展开入口'), 'product rules should document collapsible metric-independent dashboard insight sections')
})

test('problem card list supports category filtering and counterfeit wording', () => {
  const js = read('miniprogram-card/pages/index/index.js')
  const wxml = read('miniprogram-card/pages/index/index.wxml')
  const wxss = read('miniprogram-card/pages/index/index.wxss')
  const detail = read('miniprogram-card/pages/detail/detail.wxml')
  assert(js.includes('CATEGORY_FILTER_OPTIONS'))
  assert(js.includes('setCategoryFilter'))
  assert(js.includes('(card.category || \'fake-patch\') !== activeCategory'))
  assert(!wxml.includes('全部球员'))
  assert(!wxml.includes('全部品牌'))
  assert(!wxml.includes('全部年份'))
  assert(wxml.includes('category-filter-tag'))
  assert(wxml.includes('假卡'))
  assert(wxml.includes('换 Patch'))
  assert(wxss.includes('.category-filter-tag.active { background: #667eea; color: #fff;'))
  assert(!wxss.includes('.category-filter-tag.active { background: #111827;'))
  const disclaimer = '请仔细查看来源资料或者当前页面相关信息后再做判断，本网站不构成任何鉴定结论、交易建议或维权证据。'
  assert(detail.includes(`这张卡已进入明确 Patch 异常记录：同一张卡出现 Patch 不一致，或已有明确换 Patch / 来源冲突记录。${disclaimer}`))
  assert(detail.includes(`这张卡已进入高度存疑 Patch 线索：疑点来自同款卡 Patch 材质、位置、复杂度或球队/年份合理性对比，但尚未形成明确结论。${disclaimer}`))
  assert.strictEqual(detail.split(disclaimer).length - 1, 6)
  assert(!detail.includes('请仔细查看来源资料后再做判断。'))
  assert(!detail.includes('本资料仅供参考'))
  assert(!detail.includes('具体信息请查看资料来源'))
  assert(!detail.includes('不应按普通同款差异理解'))
  assert(detail.includes('假卡仅凭图片通常难以完全判断'))
})

test('feedback submission warns when a likely duplicate problem card exists', () => {
  const js = read('miniprogram-card/pages/feedback/feedback.js')
  assert(js.includes('function normalizeDuplicateText'))
  assert(js.includes('findDuplicateCandidates'))
  assert(js.includes('confirmDuplicateIfNeeded'))
  assert(js.includes('可能重复'))
  assert(js.includes('继续反馈'))
})

test('feedback submission requires a public user id separate from source', () => {
  const js = read('miniprogram-card/pages/feedback/feedback.js')
  const wxml = read('miniprogram-card/pages/feedback/feedback.wxml')
  const adminJs = read('miniprogram-card/pages/admin/admin.js')
  const adminWxml = read('miniprogram-card/pages/admin/admin.wxml')
  const adminOps = read('miniprogram-card/cloudfunctions/adminOps/index.js')
  const detailWxml = read('miniprogram-card/pages/detail/detail.wxml')
  assert(js.includes('loadPublicUserProfile'), 'feedback page should load the same public id profile as series uploads')
  assert(js.includes('ensureFeedbackPublicUserId'), 'feedback submit should validate or create the public id')
  assert(js.includes('submitterPublicId'), 'feedback records should store public id separately')
  assert(wxml.includes('反馈用户 ID'), 'feedback form should ask for a feedback public id')
  assert(wxml.includes('资料来源'), 'source field should remain separate')
  assert(adminJs.includes('submitterPublicId: approveForm.submitterPublicId'), 'approval should carry public id through cardInfo')
  assert(adminWxml.includes('反馈用户'), 'admin detail should display the feedback public id')
  assert(adminOps.includes('submitterPublicId: cleanCardInfo.submitterPublicId || feedback.submitterPublicId ||'), 'approved cards should keep public id')
  assert(detailWxml.includes('card.submitterPublicId'), 'problem card detail should display public id separately from source')
})

test('problem card detail source supports long-press copy', () => {
  const detailWxml = read('miniprogram-card/pages/detail/detail.wxml')
  const detailJs = read('miniprogram-card/pages/detail/detail.js')
  assert(detailWxml.includes('bindlongpress="copySource"'), 'problem card source should support long-press copy')
  assert(detailWxml.includes('user-select="{{true}}"'), 'problem card source should be text-selectable')
  assert(detailJs.includes("title: '已复制来源'"), 'copy toast should work for all source text, not only links')
})

test('problem card feedback copy uses anomaly feedback wording', () => {
  const feedbackJson = read('miniprogram-card/pages/feedback/feedback.json')
  const feedbackWxml = read('miniprogram-card/pages/feedback/feedback.wxml')
  const feedbackJs = read('miniprogram-card/pages/feedback/feedback.js')
  const indexWxml = read('miniprogram-card/pages/index/index.wxml')
  const guideWxml = read('miniprogram-card/pages/guide/guide.wxml')
  const adminWxml = read('miniprogram-card/pages/admin/admin.wxml')
  const adminJs = read('miniprogram-card/pages/admin/admin.js')
  const detailWxml = read('miniprogram-card/pages/detail/detail.wxml')
  assert(feedbackJson.includes('反馈异常卡片'), 'feedback page title should use anomaly feedback wording')
  assert(indexWxml.includes('反馈异常卡片'), 'home entry should use anomaly feedback wording')
  assert(guideWxml.includes('如何反馈异常卡片？'), 'guide should explain anomaly feedback')
  assert(feedbackWxml.includes('反馈人信息'), 'feedback form should use feedback submitter wording')
  assert(feedbackWxml.includes('提交异常反馈'), 'primary button should describe the submit action clearly')
  assert(feedbackJs.includes('反馈已提交'), 'success toast should use feedback wording')
  assert(feedbackJs.includes('反馈失败，请重试'), 'failure toast should use feedback wording')
  assert(adminWxml.includes('总反馈'), 'admin stats should use feedback wording')
  assert(adminWxml.includes('异常反馈'), 'admin tab should use anomaly feedback wording')
  assert(adminWxml.includes('暂无异常反馈'), 'admin empty state should use feedback wording')
  assert(adminJs.includes('这条异常反馈'), 'admin reject dialog should use feedback wording')
  assert(detailWxml.includes('反馈资料修正'), 'detail correction modal should avoid submit-material wording')
  assert(!indexWxml.includes('提交资料'), 'home entry should not use old submit-material wording')
  assert(!adminWxml.includes('资料提交'), 'admin tab and comments should not use old submit-material wording')
})

test('admin and detail edit modals reserve footer space on real devices', () => {
  const adminWxss = read('miniprogram-card/pages/admin/admin.wxss')
  const detailWxss = read('miniprogram-card/pages/detail/detail.wxss')
  assert(adminWxss.includes('.approve-panel {\n  height: 90vh;'), 'admin upload/edit modals should have a fixed flex height')
  assert(adminWxss.includes('min-height: 0;'), 'admin modal scroll body should be allowed to shrink inside flex layout')
  assert(adminWxss.includes('.approve-form {\n  padding-bottom: 180rpx;'), 'admin form content should leave room above the fixed footer')
  assert(adminWxss.includes('.modal-footer .submit-approve {\n  width: 100%;\n  max-width: 560rpx;'), 'admin modal footer button should be centered with stable width')
  assert(detailWxss.includes('.edit-panel {\n  width: 100%;\n  height: 85vh;'), 'detail edit modal should have a fixed flex height')
  assert(detailWxss.includes('.edit-modal-body {\n  max-height: none;'), 'detail edit modal body should not use a competing viewport max-height')
  assert(detailWxss.includes('.edit-form {\n  padding-top: 0;\n  padding-bottom: 180rpx;'), 'detail edit form should leave room above the fixed footer')
  assert(detailWxss.includes('.save-edit-btn {\n  width: 100%;\n  max-width: 560rpx;'), 'detail edit save button should be centered with stable width')
})

test('admin and detail edit modals use feedback-style section cards', () => {
  const adminWxss = read('miniprogram-card/pages/admin/admin.wxss')
  const detailWxss = read('miniprogram-card/pages/detail/detail.wxss')
  assert(adminWxss.includes('background: #f5f7fa;'), 'admin modal body should use a soft gray form background')
  assert(adminWxss.includes('.modal-section {\n  padding: 32rpx;\n  margin-bottom: 24rpx;\n  background: #fff;\n  border-radius: 20rpx;'), 'admin modal sections should render as card blocks')
  assert(adminWxss.includes('border-left: 6rpx solid #667eea;'), 'admin section titles should match feedback page hierarchy')
  assert(detailWxss.includes('background: #f5f7fa;'), 'detail modal body should use a soft gray form background')
  assert(detailWxss.includes('.modal-section {\n  padding: 32rpx;\n  margin-bottom: 24rpx;\n  background: #fff;\n  border-radius: 20rpx;'), 'detail modal sections should render as card blocks')
  assert(detailWxss.includes('border-left: 6rpx solid #667eea;'), 'detail section titles should match feedback page hierarchy')
})

test('card image uploads support front back and detail images', () => {
  const seriesJs = read('miniprogram-card/pages/collection-series/collection-series.js')
  const seriesWxml = read('miniprogram-card/pages/collection-series/collection-series.wxml')
  const myJs = read('miniprogram-card/pages/my-collection/my-collection.js')
  const myWxml = read('miniprogram-card/pages/my-collection/my-collection.wxml')
  const detailJs = read('miniprogram-card/pages/collection-card-detail/collection-card-detail.js')
  const seriesOps = read('miniprogram-card/cloudfunctions/seriesOps/index.js')
  assert(seriesJs.includes('detailImageUrls: []'), 'series image metadata should include detail image URLs')
  assert(seriesJs.includes('_buildUploadItemsFromSelectedFiles'), 'series upload should map one multi-select batch to one card image record')
  assert(seriesJs.includes('item.backTempFilePath = paths[1] ||'), 'second selected image should default to back image')
  assert(seriesJs.includes('item.detailTempFilePaths = paths.slice(2)'), 'remaining selected images should default to detail images')
  assert(seriesWxml.includes('细节图'), 'series upload modal should expose detail images')
  assert(seriesWxml.includes('chooseUploadItemDetails'), 'series upload modal should allow adding detail images')
  assert(myJs.includes("const count = field === 'imageUrl' ? 9 : 1"), 'my collection front image picker should support multi-select')
  assert(myJs.includes("'form.detailImageUrls': paths.slice(2)"), 'my collection multi-select should map remaining images to details')
  assert(myWxml.includes('chooseDetailImages'), 'my collection modal should allow detail images')
  assert(detailJs.includes('img.detailImageUrls'), 'collection card detail should include detail images in the carousel')
  assert(seriesOps.includes('detailImageUrls: Array.isArray(input.detailImageUrls)'), 'cloud function should persist user card detail image URLs')
})
