const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const indexHtml = read('card/index.html')
const appJs = read('card/js/app.js')
const detailJs = read('card/js/detail.js')
const collectionDetailJs = read('card/js/collection-detail.js')
const collectionJs = read('card/js/collection.js')
const collectionDataJs = read('card/js/collection-data.js')
const dataJs = read('card/js/data.js')
const syncJs = read('card/sync.js')
const cardCss = read('card/css/style.css')
const miniDetailCss = read('miniprogram-card/pages/detail/detail.wxss')

assert(indexHtml.includes('鉴别资料库'), 'home tab should use 鉴别资料库 wording')
assert(indexHtml.includes('查卡避坑·资料参考'), 'home tab subtitle should match mini program positioning')
assert(!indexHtml.includes('问题球星卡'), 'old problem-card tab wording should be removed from web home')
assert(indexHtml.includes('categoryFilterTags'), 'web home should expose mini-program style category filters')
assert(!indexHtml.includes('id="playerFilter"'), 'web home should remove player filter select')
assert(!indexHtml.includes('id="brandFilter"'), 'web home should remove brand filter select')
assert(!indexHtml.includes('id="yearFilter"'), 'web home should remove year filter select')

assert(appJs.includes("'高度存疑'"), 'web list should display suspected records as 高度存疑')
assert(appJs.includes("'明确异常'"), 'web list should display confirmed records as 明确异常')
assert(appJs.includes("'换 Patch'"), 'category label should use 换 Patch')
assert(appJs.includes("'签字异常'"), 'category label should use 签字异常')
assert(appJs.includes("'假卡'"), 'category label should use 假卡')
assert(appJs.includes('buildKeywordTerms'), 'web search should support tokenized combo search')
assert(appJs.includes('buildCardSearchText'), 'web search should search against a combined card text index')
assert(appJs.includes('setCategoryFilter'), 'web category chips should switch the active type filter')
assert(!appJs.includes('collection.renderInto'), 'tab switching should not call a missing collection render API')

assert(detailJs.includes('资料提示：明确异常记录'), 'detail confirmed title should use 明确异常记录')
assert(detailJs.includes('资料提示：高度存疑线索'), 'detail suspected title should use 高度存疑线索')
assert(detailJs.includes('问题说明'), 'detail high-risk reason label should be 问题说明')
assert(detailJs.includes('异常样本'), 'detail after image label should use 异常样本')
assert(detailJs.includes('原始 Patch 参考'), 'detail before image label should use 原始 Patch 参考')
assert(detailJs.includes('不构成鉴定结论、交易建议或维权依据'), 'detail should show compliance disclaimer')
assert(!detailJs.includes('用户实拍'), 'static problem detail should not expose user-photo wording')
assert(!detailJs.includes('用户投稿'), 'static problem detail should not expose user-submission wording')
assert(detailJs.includes('sanitizePublicSourceText'), 'static problem detail should sanitize user wording from text sources')

assert(collectionDetailJs.includes('shouldShowImageYear'), 'collection image labels should decide whether repeated year is useful')
assert(collectionDetailJs.includes('getSeriesKnownYears'), 'collection detail should detect years already defined by the series')
assert(!collectionDetailJs.includes('用户实拍'), 'static collection detail should not expose user-photo wording')
assert(!collectionDetailJs.includes('用户投稿'), 'static collection detail should not expose user-submission wording')
assert(!collectionDetailJs.includes('上传用户'), 'static collection detail should not expose uploader wording')
assert(collectionDetailJs.includes('sanitizePublicSourceText'), 'static collection detail should sanitize user wording from source notes')
assert(collectionJs.includes('if (rawTarget === 0) total = 0'), 'static collection list should respect disabled completion targets')
assert(collectionDetailJs.includes('if (rawTarget === 0) total = 0'), 'static collection detail should respect disabled completion targets')
assert(!collectionDataJs.includes('ownedBy'), 'static collection payload should not ship ownership fields')
assert(!collectionDataJs.includes('uploaderOpenid'), 'static collection payload should not ship uploader openid fields')
assert(!collectionDataJs.includes('uploaderPublicId'), 'static collection payload should not ship uploader public id fields')
assert(!dataJs.includes('小程序用户反馈'), 'static problem-card payload should not expose user-feedback wording')
assert(!syncJs.includes('ownedBy'), 'static sync should not regenerate ownership fields')
assert(!syncJs.includes('uploaderOpenid'), 'static sync should not regenerate uploader fields')

assert(/\.warning-danger\s*{[^}]*background:\s*#fee2e2/i.test(cardCss), 'web confirmed warning should use a stronger red background')
assert(/\.warning-danger\s*{[^}]*border-left:\s*4px solid #ef4444/i.test(cardCss), 'web confirmed warning should use a red border')
assert(/\.category-filter-tag\.active\s*{[^}]*background:\s*#667eea/i.test(cardCss), 'web active category chip should use mini-program blue')
assert(/\.warning-danger\s*{[^}]*background:\s*#fee2e2/i.test(miniDetailCss), 'mini confirmed warning should use a stronger red background')
assert(/\.warning-danger \.warning-desc\s*{[^}]*color:\s*#991b1b/i.test(miniDetailCss), 'mini confirmed warning text should be red, not gray')

console.log('static display copy tests passed')
